
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-12
owner: ucsb-cs156-f25
repo_name: team01-f25-12
pull_requests: [{"author":{"id":"U_kgDOCvDUNQ","is_bot":false,"login":"TejTripathyUCSB","name":""},"headRefName":"tst-delete","number":71,"title":"adds the delete function and the testing for the dining commons menu item - tej ","url":"https://github.com/ucsb-cs156-f25/team01-f25-12/pull/71"},{"author":{"id":"U_kgDOCvDUNQ","is_bot":false,"login":"TejTripathyUCSB","name":""},"headRefName":"tst-addput","number":69,"title":"adds the put function for ucsb dining commons menu item. - tej ","url":"https://github.com/ucsb-cs156-f25/team01-f25-12/pull/69"},{"author":{"id":"U_kgDOC6IUpQ","is_bot":false,"login":"joshua-dev-codes","name":""},"headRefName":"ja-create-recommendation-request-controller","number":64,"title":"Ja create recommendation request controller adding get all and post methods","url":"https://github.com/ucsb-cs156-f25/team01-f25-12/pull/64"},{"author":{"id":"U_kgDOC6IUpQ","is_bot":false,"login":"joshua-dev-codes","name":""},"headRefName":"joshua-dev-codes-RecommendationRequest-create-db","number":59,"title":"created db table for recommendation requests","url":"https://github.com/ucsb-cs156-f25/team01-f25-12/pull/59"},{"author":{"id":"U_kgDOCvDUNQ","is_bot":false,"login":"TejTripathyUCSB","name":""},"headRefName":"tst-addgetbyid","number":54,"title":"tst - added the code and test for get by id","url":"https://github.com/ucsb-cs156-f25/team01-f25-12/pull/54"}]
