
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-12
owner: ucsb-cs156-f25
repo_name: team01-f25-12
pull_requests: [{"author":{"id":"U_kgDODXgFtA","is_bot":false,"login":"yibinjiang04","name":""},"headRefName":"bj-delete-for-article-table","number":61,"title":"Bj delete for article table","url":"https://github.com/ucsb-cs156-f25/team01-f25-12/pull/61"},{"author":{"id":"U_kgDODXgFtA","is_bot":false,"login":"yibinjiang04","name":""},"headRefName":"bj-put-for-article-table","number":60,"title":"Bj put for article table","url":"https://github.com/ucsb-cs156-f25/team01-f25-12/pull/60"},{"author":{"id":"U_kgDOC6IUpQ","is_bot":false,"login":"joshua-dev-codes","name":""},"headRefName":"joshua-dev-codes-RecommendationRequest-create-db","number":59,"title":"created db table for recommendation requests","url":"https://github.com/ucsb-cs156-f25/team01-f25-12/pull/59"},{"author":{"id":"U_kgDOCQQjrw","is_bot":false,"login":"AlvinLovesCode","name":""},"headRefName":"remotes/origin/Alvin-MenuItemReview-Controller","number":58,"title":"Created menu item review controller with Get/Post  endpoints","url":"https://github.com/ucsb-cs156-f25/team01-f25-12/pull/58"},{"author":{"id":"U_kgDODXgFtA","is_bot":false,"login":"yibinjiang04","name":""},"headRefName":"bj-articles-get-by-id","number":57,"title":"Bj - add GET by id for articles","url":"https://github.com/ucsb-cs156-f25/team01-f25-12/pull/57"},{"author":{"id":"U_kgDODXgFtA","is_bot":false,"login":"yibinjiang04","name":""},"headRefName":"bj-create-article-controller","number":55,"title":"Bj create article controller, add GET /all and POST methods","url":"https://github.com/ucsb-cs156-f25/team01-f25-12/pull/55"},{"author":{"id":"U_kgDOCvDUNQ","is_bot":false,"login":"TejTripathyUCSB","name":""},"headRefName":"tst-addgetbyid","number":54,"title":"tst - added the code and test for get by id","url":"https://github.com/ucsb-cs156-f25/team01-f25-12/pull/54"},{"author":{"id":"U_kgDOBaYVeg","is_bot":false,"login":"HRehwald","name":"Hauke Rehwald"},"headRefName":"GetPostHelpRequest-Hauke","number":53,"title":"Get post help request hauke","url":"https://github.com/ucsb-cs156-f25/team01-f25-12/pull/53"},{"author":{"id":"U_kgDOCqFMyA","is_bot":false,"login":"jaytan3966","name":"Jayden Tan"},"headRefName":"17-add-put-endpoint-for-a-single-record-in-ucsborganization-table","number":48,"title":"created PUT endpoint + test functions for UCSBOrganizations","url":"https://github.com/ucsb-cs156-f25/team01-f25-12/pull/48"}]
