
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-12
owner: ucsb-cs156-f25
repo_name: team01-f25-12
pull_requests: [{"author":{"id":"U_kgDOCvDUNQ","is_bot":false,"login":"TejTripathyUCSB","name":""},"headRefName":"tst-create-menuitemcontroller-addget","number":52,"title":"TEJ - CREATE THE GET AND PUT COMMANDS WITH TEST COVERAGE ","url":"https://github.com/ucsb-cs156-f25/team01-f25-12/pull/52"},{"author":{"id":"U_kgDOBaYVeg","is_bot":false,"login":"HRehwald","name":"Hauke Rehwald"},"headRefName":"Hauke-HelpTable2","number":49,"title":"Hauke database setup for HelpRequests","url":"https://github.com/ucsb-cs156-f25/team01-f25-12/pull/49"},{"author":{"id":"U_kgDOCqFMyA","is_bot":false,"login":"jaytan3966","name":"Jayden Tan"},"headRefName":"17-add-put-endpoint-for-a-single-record-in-ucsborganization-table","number":48,"title":"created PUT endpoint + test functions for UCSBOrganizations","url":"https://github.com/ucsb-cs156-f25/team01-f25-12/pull/48"}]
