name: 00 - All Checks Pass

# This workflow checks if all required checks have passed before allowing a pull request to be merged.
# It is triggered on pull request events and uses the GitHub CLI to check the status of checks.
# The workflow will wait for all other checks to finish before proceeding.
# If any of the required checks fail, the workflow will exit with an error.


# This workflow updates the open PRs in
# _config.yml each time a pull request is made
# or there is a push to main.  It does not handle
# the rebuild of the storybook or javadoc; that's handled
# separately based on which files were modified.

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
          

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: read


# The name "enforce" for this job is important; do not change it. The
# ucsb-cs156/workflows repository expects this name in order to
# identify this job.  It is also used in the "Required checks" section
# of the branch protection rules for the main branch.

jobs:
  enforce: # the name "enforce" is important here; do not change it (see above)
    uses: ucsb-cs156/workflows/.github/workflows/00-all-checks-pass.yml@main
    secrets: 
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

